### ISSUE TITLE
upload videos similar to [pahe] scss 

### ISSUE THREAD

**Issue by ghost** [SpEcHiDe/PublicLeech#11]
Can we have a watermark option on upload with and without custom thumbnails. And a command for cancelall or restart.

**Comment by SpEcHiDe** [comment]
thumbnail is already available. 

cancelall and restart are not available.

**Comment by mukeshz** [comment]
I mean Watermark on thumbnail and watermark on videos without thumbnails. I know custom thumbnail is available I am using it and Loving It ❤❤

**Comment by SpEcHiDe** [comment]
Partially done in https://github.com/SpEcHiDe/PublicLeech/commit/c2e0920909bd34285b54586f85c85cc99f017cc7

**Comment by SpEcHiDe** [comment]
https://t.me/c/1220993104/600839
