### ISSUE TITLE
Heroku Deploy

### ISSUE THREAD

**Issue by BeratungsResistent** [SpEcHiDe/PublicLeech#114]
Hi, give us heroku deploy back again.

**Comment by SpEcHiDe** [comment]
IT US RECOMMENDED TO LEARN [@PythonRes](https://t.me/UniBorg/27) before you attempt to run anything, by yourself.

**Comment by UdayKumarChunduru** [comment]
I want to create my own leech bot.
But when I came here it's not there in heroku to deploy.
Could you please give that back😟
