### ISSUE TITLE
videos without audio

### ISSUE THREAD

**Issue by SpEcHiDe** [SpEcHiDe/PublicLeech#122]
currently, only youtube videos are handled with this condition, https://github.com/SpEcHiDe/PublicLeech/blob/master/tobrot/helper_funcs/youtube_dl_button.py#L117, but we can't know which formats will have audios untill we explicitly download and tweak, 

- [ ] check if there is any generic method, to identify when yo use +bestaudio toggle, and when not to.

**Comment by anon97945** [comment]
Don't know how to fetch the choosen format description.
Code would be like


      minus_f_format = youtube_dl_format
        if "video only" in youtube_dl_format_desc and not "youtu" in youtube_dl_url:
            minus_f_format = youtube_dl_format + "+bestaudio"
