### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by flmorse** [SpEcHiDe/PublicLeech#138]
I successfully deployed the bot. But when I send a torrent link and try to leech it the bot get stuck with the messege "extracting links". And the terminal displays the follwing issue.

FileNotFoundError: [Errno 2] No such file or directory: 'aria2c': 'aria2c'

![image](https://user-images.githubusercontent.com/69221003/101295327-fd15e680-3842-11eb-8848-1533777723f0.png)

![image](https://user-images.githubusercontent.com/69221003/101295336-0bfc9900-3843-11eb-8b83-3286653fabaf.png)

**Comment by SpEcHiDe** [comment]
READ THE README, and USE DOCKER.
