### ISSUE TITLE
How to use legacy way to Deploy [question] 

### ISSUE THREAD

**Issue by Poppit-pop** [SpEcHiDe/PublicLeech#144]
Can you please help me to deploy this code using legacy way. I installed git, furst step was easy but how to use other steps [python3 -m venv venv
. ./venv/bin/activate
pip install -r requirements.txt
python3 -m tobrot]?

**Comment by SpEcHiDe** [comment]
https://t.me/PublicLeechGroup/208

**Comment by Poppit-pop** [comment]
> https://t.me/PublicLeechGroup/208

Thank you

**Comment by IshwaranRudhara** [comment]
UNCLE! heroku based? ploxx!
:)
