### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'from_user

### ISSUE THREAD

**Issue by rockydares** [SpEcHiDe/PublicLeech#147]
![Capture](https://user-images.githubusercontent.com/66517282/109348244-469e2c80-789a-11eb-84f2-bc0a301ea7d5.PNG)

### Is there any method to run this thing manually other than installing docker on my machine?

**Comment by SayanthD** [comment]
@rockydares This issue seems to be occurring when the bot is used in PM. To resolve this either,
1. Add the bot in a supergroup and set AUTH_CHANNEL with chat id
2. Use BUTTONs mode

**Comment by rockydares** [comment]
> @rockydares This issue seems to be occurring when the bot is used in PM. To resolve this either,
> 
> 1. Add the bot in a supergroup and set AUTH_CHANNEL with chat id
> 2. Use BUTTONs mode

This seems to be working and has resolved the problem. Thank you.

**Comment by IshwaranRudhara** [comment]
> @rockydares This issue seems to be occurring when the bot is used in PM. To resolve this either,
> 
> 1. Add the bot in a supergroup and set AUTH_CHANNEL with chat id
> 2. Use BUTTONs mode

PRU!

**Comment by rockydares** [comment]
> @rockydares This issue seems to be occurring when the bot is used in PM. To resolve this either,
> 
> 1. Add the bot in a supergroup and set AUTH_CHANNEL with chat id
> 2. Use BUTTONs mode

Ok so another problem occured i.e. whenever I'm trying to upload any new file via URL or magnet link, after downloading it for some percentage the file gets cancelled and I get this msg from the bot,
"unable to download upload
#stopped
manually clear storage (/upload) using GNU/Linux commands"

I'm clearing the storage, manually deleting those partially downloaded files and when I retry downloading them, same thing happens. When I put _/status_ command, the bot sends a looong list of files which I have already uploaded or got cancelled. I tried removing _aria2_ and reinstalling, remove PublicLeech and retry it from begining, this problem persists. The long list of files names (which is showing by /status command) seems to be not going and thus no new files are getting uploded.

Btw, I had an old version of PublicLeech forked in my account which was the best version of it (in my opinion), somehow I manged to make it work by changing it's _asyncio-dev_ link (from requirements.txt) as the old link shows 404 error while installing via pip. Now it works perfectly fine without any kind of errors I was facing earlier.  I can use it in groups or in private. I can give you the link of that old version if you care. 
Thank you again.
