### ISSUE TITLE
aria2c out

### ISSUE THREAD

**Issue by muhammedfurkan** [SpEcHiDe/PublicLeech#21]
https://github.com/SpEcHiDe/PublicLeech/blob/e15cf94a3fc6251f997a134301350b52fcefa49e/tobrot/helper_funcs/download_aria_p_n.py#L35

aria2c `aria2_daemon_start_cmd.append(f"--dir={DOWNLOAD_LOCATION}")` working

**Comment by SpEcHiDe** [comment]
it did not work when I had tried in Heroku. 

What value did you give for DOWNLOAD_LOCATION ?
