### ISSUE TITLE
shit posting issue 🤒🤒😢 help me

### ISSUE THREAD

**Issue by Abhishek890** [SpEcHiDe/PublicLeech#22]
Why Our bot don't get download speed and upload speed like your bot can you say all your config you done for your bot with values
Everyone has Uploading and downloading speed issue

**Comment by SpEcHiDe** [comment]
😐🤤🤤

**Comment by Abhishek890** [comment]
bro atleast help me download speed is now good but upload speed is max 300kb

**Comment by Abhishek890** [comment]
atleast recommend some setting and values

**Comment by Abhishek890** [comment]
should i edit CHUNK_SIZE

**Comment by fr54nk** [comment]
It's most probably a server issue. If you get a good server you can get up to 2-5bmbps upload speed to telegram servers
