### ISSUE TITLE
Help me i am paying 500$ to heroku but no speed then also

### ISSUE THREAD

**Issue by Abhishek890** [SpEcHiDe/PublicLeech#23]
i am not getting good upload speed after paying 500$ to heroku help see my ss andything wrong 

![image](https://user-images.githubusercontent.com/46078948/75447019-82a06800-598e-11ea-9f08-16460753fc14.png)
![image](https://user-images.githubusercontent.com/46078948/75447043-92b84780-598e-11ea-80f9-3e37082ba0e1.png)

is anything wrong say me proper value i will fix it help me guys

**Comment by CW4RR10R** [comment]
You can get a flagship server for 500$ then why are you still using heroku 😪🤔🙄

**Comment by fr54nk** [comment]
Adding to CW4RR10R's suggestion, you can move to Google cloud or digital ocean if you're paying. They seem to be better I presume

**Comment by Abhishek890** [comment]
ok

**Comment by Omkar47** [comment]
I you talking about telegram upload speed then its on telegram not on heroku(atleast not totally)
