### ISSUE TITLE
Request Seed and peers info

### ISSUE THREAD

**Issue by cdfxscrq** [SpEcHiDe/PublicLeech#25]
Request to create a seeds and peers information on downloading . It's helpful for members . Thank you !!!!!💐

**Comment by cdfxscrq** [comment]
Name: Pettai.avi
Status: Downloading
[▓▓▓▓▓▓▓▓▓▓▓░░] 83.55% of 4.58 GiB
Speed: 5.71 MiB/s   ETA: 12m5s 


**(Info:  P : 20  || S : 11 ||  )**  <--This is the example !!!!

**Comment by SpEcHiDe** [comment]
done in #32
