### ISSUE TITLE
Feature to upload in cloud service!

### ISSUE THREAD

**Issue by a092devs** [SpEcHiDe/PublicLeech#3]
Add a feature to upload in gdrive. If not gdrive, then atleast use transfer.sh as uploading to telegram doesn't makes any sense. The downliad speed is slow compared to other services, also, it will save time.

**Comment by SpEcHiDe** [comment]
all public cloud services have file size Limitations. 

Telegram on the other hand has no file size Limitations, for bot accounts*.

So,... 😅😅😕😕😕

**Comment by SpEcHiDe** [comment]
reopening because https://download.upload.workers.dev/AwADBQADDAYAAvYrcVRT0-UxGuZcmAI/voice

**Comment by gautamajay52** [comment]
Sar are u going to add the uploading to gdrive using rclone???🤔🤔

**Comment by SpEcHiDe** [comment]
Yes. All thanks to you for the "inspiration".

**Comment by gautamajay52** [comment]
> Yes. All thanks to you for the "inspiration".

Now time to close all things...
ur repo will be on 🔥😚

**Comment by SpEcHiDe** [comment]
you can now configure rclone.conf with this commit https://github.com/SpEcHiDe/PublicLeech/commit/dc21fb47aa5a2242ada97dc7e0dffaf8cd230bfb
