### ISSUE TITLE
Leech through torrent file?

### ISSUE THREAD

**Issue by mikan01** [SpEcHiDe/PublicLeech#30]
How to download the torrent from torrent file instead of magnet links?

I tried to download to torrent file, leecher doesn't work as intended.

Any options?

**Comment by SpEcHiDe** [comment]
check the available commands in stdplugins > aria_two.py

**Comment by SpEcHiDe** [comment]
current workaround is to forward TORRENT file to any of the 

@LinkToFilesBot
@FilesToLinkBot
@LinkForFileBot
@FilesToIinkBot
@HK_Link_Bot

and send the returned link, and leech it.
