### ISSUE TITLE
Magnet link don't work

### ISSUE THREAD

**Issue by studiosam** [SpEcHiDe/PublicLeech#31]
![Annotation 2020-04-21 144138](https://user-images.githubusercontent.com/31368322/79867194-3b5ab480-83de-11ea-9dc2-11262764c5ee.png)

yt download works

**Comment by SpEcHiDe** [comment]
wrong format. Please read the code and README, to know how stuff works.

**Comment by Sunda001** [comment]
@studiosam Hmm

**Comment by kalmengr** [comment]
@studiosam Can I make the bot send unsolicited messages?

**Comment by studiosam** [comment]
> @studiosam Can I make the bot send unsolicited messages?

what you want to try ?
