### ISSUE TITLE
Downloading of certain youtube as mp3

### ISSUE THREAD

**Issue by anon97945** [SpEcHiDe/PublicLeech#56]
Hello, we already spoke, some videos can't be uploaded as mp3... It just stays at "downloading" process. Actually its the Link i posted below for which i try to figure out the error. Some others working fine... It didn't "upload" as 64kb, 128kb or 320kb. As video its fine, but the filesizes aren't exact, at 144p its telling 456mb but its actually 1,1gb uploading :-D

However, the problem is as Music file....

https://youtu.be/ntu4ik4otfo

**Comment by SpEcHiDe** [comment]
Possible Issue Reason: https://t.me/c/1424718830/31414

Need to check the workarounds

**Comment by anon97945** [comment]
Cant see the link; Want to add that Videos are uploaded after HELL of a time. So its something with the encoder or whatever... a 10hours Music Video downloaded as 320kb takes about 45+ Minutes. AnyDLBot does this within 40 Seconds, dont know the difference in ytdl from AnyDL to PublicLeech. Should be worth to look into.
