### ISSUE TITLE
Bot stuck when downloading

### ISSUE THREAD

**Issue by Bartixxx32** [SpEcHiDe/PublicLeech#6]
I have problem, bot stuck with reason FLOOD_WAIT_X
im guess i need add some env to message sending timeout or so but i`m dont know whats the var is

![image](https://user-images.githubusercontent.com/16412925/71606189-1f04e480-2b6f-11ea-9613-031426778c6e.png)

![image](https://user-images.githubusercontent.com/16412925/71606193-25935c00-2b6f-11ea-8159-61fe652e26d9.png)

![image](https://user-images.githubusercontent.com/16412925/71606251-86229900-2b6f-11ea-9705-c035118a99bd.png)

**Comment by SpEcHiDe** [comment]
please give proper values for `EDIT_SLEEP_TIME_OUT` and `MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START`.

**Comment by AdzeB** [comment]
> MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START

Where please?

**Comment by cdfxscrq** [comment]
Some problems sir
EDIT_SLEEP_TIME_OUT - 1
MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START - empty

**Comment by kumars4you** [comment]
> please give proper values for `EDIT_SLEEP_TIME_OUT` and `MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START`.

Bro, give me proper value🙏🙏🙏

**Comment by cdfxscrq** [comment]
> > please give proper values for `EDIT_SLEEP_TIME_OUT` and `MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START`.
> 
> Bro, give me proper value, please...

Sleep time out and wait for torrent change to 30

**Comment by shadow443** [comment]
There will be some other configuration for torrent?

**Comment by shadow443** [comment]
I installed the bot in a vps and I have the same problem as "FLOOD_WAIT_X".
