### ISSUE TITLE
Is there any way to get files as Forced Documents

### ISSUE THREAD

**Issue by AKJ13** [SpEcHiDe/PublicLeech#61]
Both mkv and mp4 appears as streamable videos, is there any way to make it forced documents?

**Comment by SpEcHiDe** [comment]
out of curiosity, why would you want it as documents? 
Video Files on Telegram have many advantages: https://t.me/c/1039510406/1599

**Comment by SpEcHiDe** [comment]
I could add an ENV var in the code, to force uploading as documents, but I don't like it. 
Read: https://t.me/c/1092696260/521252
