### ISSUE TITLE
Pinned Message Not Working

### ISSUE THREAD

**Issue by coolviraj** [SpEcHiDe/PublicLeech#64]
Any member join group than bot send automatically message in this message please read pinned message...
User click on this message it's not open and show error message doesn't exist

**Comment by Muttahir786** [comment]
Well currently u need to specify message id in ur fork cuz it is hardcoded.

**Comment by coolviraj** [comment]
Yes
 Whenever it fix 
Can i edit source code

??

**Comment by SpEcHiDe** [comment]
__main__.py

**Comment by coolviraj** [comment]
Ok i tried
If not work i will ping you

And yes how to download without replay command like /leech or /ytdl
Just click and past Download will start...

**Comment by coolviraj** [comment]
Solve
