### ISSUE TITLE
without replay any commands

### ISSUE THREAD

**Issue by coolviraj** [SpEcHiDe/PublicLeech#65]
how to download without replay command like /leech or /ytdl
Just click and past Download will start...

**Comment by Muttahir786** [comment]
u mean autodetect?
or something like /leech magnet

**Comment by coolviraj** [comment]
Yes Auto detect

**Comment by Muttahir786** [comment]
> Yes Auto detect

not available yet.

**Comment by coolviraj** [comment]
Ok

**Comment by coolviraj** [comment]
Batado sir kaise auto command...please

**Comment by gautamajay52** [comment]
Go and change command handler filter to regex.

**Comment by coolviraj** [comment]
Where??

**Comment by gautamajay52** [comment]
In tobrot/main.py
Now plz don't ask me to do so.🤒🤒🧘

**Comment by Muttahir786** [comment]
> In tobrot/main.py
> Now plz don't ask me to do so.

why not
