### ISSUE TITLE
upload getting timed out

### ISSUE THREAD

**Issue by sethazazel** [SpEcHiDe/PublicLeech#7]
Thank you for this great repository.
I don't know why but bot not working well for me.

1 - After a few seconds it stops updating progress bar.
2 - Nothing happens after download is finished. A few time trying /leech its finally starting upload.
3 - Sometimes it stops before all the uploads are finished.

Am i doing something wrong?
[Config Vars](https://i.imgur.com/OzM5l7z.jpg) 

Sorry for my bad English and thank you again.

**Comment by SpEcHiDe** [comment]
Yes. you are trying to edit the messages too fast. Please try setting a larger value for the EDIT environment value. Maybe 60. (The value is in seconds)

Let me know if it fixes your current issue.

**Comment by sethazazel** [comment]
Now it works perfectly. Thank you very much.

**Comment by sethazazel** [comment]
Now gets stuck at %100 while uploading.

**Comment by sethazazel** [comment]
I tried many times from last night to today and I only succeeded a few times. /leech archive stucks at second part generally at %75 - %100. /leech stucks at 4th-6th video. Downloads less than 1.5 GB (solid) are generally uploading without problems. I tried same torrents with other leech groups there wasn't any problem. I think i am doing something wrong but i don't know what is that.

**Comment by SpEcHiDe** [comment]
if you check the logs, you can see that the upload is timing out randomly. (At least that is when it was failing for me) it happens with any files randomly. I am still working on a fix. 😅

**Comment by dlance87** [comment]
@SpEcHiDe Hello, thanks a lot, a lot  for your atmost efforts, am having trouble with the cloned bot, as it begins to upload it says this 
FAILED 'NONE TYPE' object  has no attribute 'has'

My Config Vars are:
EDIT_SLEEP : 30
ENV: 60
MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START : 30

Hope I didn't do anything wrong, or the issue will be fixed soon?
...please help

Thanx again

**Comment by sethazazel** [comment]
I found that selecting europe when deploying with heroku was a big mistake, it was nearly never worked correctly but after i changed it to usa its started to work better.

**Comment by Abhishek890** [comment]
![image](https://user-images.githubusercontent.com/46078948/75130577-1fe06f80-56f5-11ea-9744-49c62e60d5d4.png)
i am getting this when i try to download hostar and other website torrent work finr but hostar dosent but in your publicleech group everything work fine can you say wt config you have for your  bot

**Comment by SpEcHiDe** [comment]
Fixed in https://github.com/SpEcHiDe/PublicLeech/commit/546e812b9a22eefe0ba1fd45074ff16987526e44
