### ISSUE TITLE
Telegram 2gb file support

### ISSUE THREAD

**Issue by hmntrjpt** [SpEcHiDe/PublicLeech#91]
Sir as now telegram supports file upto 2gb...so plz chngw the file splitting into 1.5gb packets to 2gb packets 👍🏻

**Comment by SpEcHiDe** [comment]
please read the README for the available configuration variables.

**Comment by gautamajay52** [comment]
> please read the README for the available configuration variables.

Too fast😬

**Comment by hmntrjpt** [comment]
Opps sry...i didn't read tht😁
