### ISSUE TITLE
File split

### ISSUE THREAD

**Issue by hmntrjpt** [SpEcHiDe/PublicLeech#92]
Sir files are splitting into 1.5gb telegram supports upto 2gb..plz chnge in to 2gb

**Comment by gautamajay52** [comment]
#91 😬

**Comment by hmntrjpt** [comment]
So r u on it?🤔

**Comment by gautamajay52** [comment]
What?🧐

**Comment by hmntrjpt** [comment]
Whn telegram split larger files..it splits into 1.5gb file each...but
telegram now supports 2gb of file...so can u chnge tht limit?

**Comment by gautamajay52** [comment]
If you want to upload split size to 1.95GB...
you should change `MAX_TG_SPLIT_FILE_SIZE` to 2097152000

And try.
